# Generated by Django 3.2.8 on 2021-12-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_serials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('serias', models.ManyToManyField(to='films.Films')),
            ],
            options={
                'verbose_name': 'Sezon',
                'verbose_name_plural': 'Sezons',
            },
        ),
        migrations.AlterField(
            model_name='serials',
            name='serias',
            field=models.ManyToManyField(to='films.Sezons'),
        ),
    ]
