# Generated by Django 3.2.8 on 2021-12-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_auto_20211212_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='serias',
            field=models.ManyToManyField(null=True, to='films.Sezons'),
        ),
    ]
