# Generated by Django 3.2.8 on 2021-12-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_serials_serias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serials',
            old_name='serias',
            new_name='sezons',
        ),
    ]
