# Generated by Django 3.2.8 on 2021-12-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_rename_serias_serials_sezons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='typef',
        ),
        migrations.AddField(
            model_name='films',
            name='typef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.type'),
        ),
    ]
