# Generated by Django 3.2.8 on 2021-12-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
