# Generated by Django 3.2.8 on 2021-12-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_auto_20211217_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.comments'),
        ),
        migrations.RemoveField(
            model_name='films',
            name='comments',
        ),
        migrations.AddField(
            model_name='films',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='films.Comments'),
        ),
    ]
