# Generated by Django 3.2.8 on 2021-12-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='serias',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='films.Comments'),
        ),
    ]
