# Generated by Django 3.2.8 on 2021-12-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0023_serials_typef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serials',
            name='typef',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='films.type'),
        ),
    ]
