# Generated by Django 3.2.8 on 2021-12-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_alter_serials_typef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='films.comments'),
        ),
        migrations.AlterField(
            model_name='films',
            name='comments',
            field=models.ManyToManyField(blank=True, to='films.Comments'),
        ),
        migrations.AlterField(
            model_name='films',
            name='typef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.type'),
        ),
        migrations.AlterField(
            model_name='serials',
            name='comments',
            field=models.ManyToManyField(blank=True, to='films.Comments'),
        ),
    ]
