# Generated by Django 3.2.8 on 2021-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='user_img/default.png', upload_to='user_img/'),
        ),
    ]
