# Generated by Django 3.2.8 on 2021-12-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='user_img/default.png', upload_to='user_img/'),
        ),
    ]
