# Generated by Django 3.2.8 on 2021-12-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_alter_serials_typef'),
        ('users', '0007_alter_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_serials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.serials'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_films',
        ),
        migrations.AddField(
            model_name='user',
            name='like_films',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.films'),
        ),
    ]
