# Generated by Django 3.2.8 on 2021-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_alter_serials_typef'),
        ('users', '0008_auto_20211217_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_films',
        ),
        migrations.AddField(
            model_name='user',
            name='like_films',
            field=models.ManyToManyField(null=True, to='films.Films'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='like_serials',
        ),
        migrations.AddField(
            model_name='user',
            name='like_serials',
            field=models.ManyToManyField(null=True, to='films.Serials'),
        ),
    ]
