# Generated by Django 3.2.8 on 2021-12-17 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211217_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends_want_add',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
